### ISSUE TITLE
平心静气的一点建议

### ISSUE THREAD

**Issue by guozhiqiang123** [xiaojinzi123/RouterGoPlugin#1]
我就是昨天ARetrofit下issues中和你吵了会的那个使用者，今天我来不是和你吵你们两个库到底是不是抄袭的。我今天花了半天时间试用了下你这个库，本着对开源精神的敬畏，我想把我的使用感受讲一下。ARouter，WMRouter,CC我和我司的小伙伴都调研过，其中CC还在正式项目中使用了一年，这些都是优秀的库，当然你这个库也很优秀，也集合了这几个库的诸多优点。但就使用效果上来说，这些库的一些缺点，你这个库也暴露的很明显。
第一：调用繁琐，即使是什么参数都不携带，也需要点4次Router .with(this) .host("component1").path("main").navigate();这在实际开发中效率会明显降低，因为CC就是这个原因，我们开发组最后选择放弃它。如果只是一个简单的跳转都需要写上至少七八行的代码，如果还有回调的话，就远不止这个数，这在实际开发中，是极其不友好的。有时候我们不得不为一个简单的跳转，甚至要单独封装一个方法；
第二，项目之所以为了组件化，除了业务的区分，更大的好处，我认为是方便多个开发者协同开发，我司Android开发3-4个人，算是比较少的了，使用git管理项目，在实际开发中遇到最多的问题就是常量的管理，因为每一个开发者命名的习惯和书写的习惯都不一样，把所有常量都下城base模块会导致要么经常命名重复（因为不是经常Git同步），要么就是同一个功能，命名了很多个常量，导致下一位开发甚至维护不了同伴写的业务逻辑，整个项目也是特别的乱；
第三：在跳转的地方设置传递参数的字段，如果是很多地方都跳转同一个页面，甚至不同的跳转还是不同的开发者写的，就会导致一个问题，时间长了或者换开发者维护这一段业务了，这些在跳转的地方传递参数的字段是什么，都在哪些地方传递过了（有的地方可能传了3个参数，有的地方可能传了4个）这样的问题使我们开发迷惑。当然这个问题使用原生的写法也非常明显
第四：你这个库单模块调试什么的，你文档里面没说，我也没仔细研究，希望补充。CC虽然书写比较繁琐，但是调试是真的方便。

这就是我试用你这个库和结合我们实际开发中遇到的问题，总结了这么四点。当然，你这个库最优秀的地方就是这个调试用的插件，所以我把issues提在这。如果CC也出这么一个插件，也许我们就不会更换了。
开源不易，希望坚持！！！祝安！！！

**Comment by xiaojinzi123** [comment]
回复一下

1. 你说的没错,这点是说的挺好的
2. 这个问题其实不会出现,应该你们应该 B 界面的跳转需要的 `path` 或者其他常量都应该 B 界面开发者来维护,责任清楚就没有这个问题
3. 这点就算你用了一个统一的方法让所有的调用都走一个方法,但是参数迷惑的问题依旧呀.其实这点的根本问题是目标界面必须在哪里可以有一个十分清晰的对入参的解释,所以这也就是你感觉用了一个统一的方法的好处,因为你就可以在这个方法上写上详细的注释,但是同时我目前想到有两个已知问题
    - 有些参数本来就是缺省的,选填的而已,你这样子就必须要传递了
    - 你对于 H5 和你 App 交互怎么办,你这样子等于放弃了基于 URI 框架天生的一个好处,当然我不清楚你用的是否支持 Uri 跳转
4. 单独调试这点我这边目前是推荐新建一个 `Module` 去包含需要调适的 `Lib` 去运行的,因为我的考虑是从 `CC` 和 其他框架的 `issue` 看来,有的会出现插件不兼容或者导致直接打包失败或者其他问题.所以我的考虑就直接放弃了这个功能.

然后我最开始评论的时候其实针对的点是你用的库的下面的用法

```
//result:Routerfit.RESULT_OK 表示回调成功 ，不调用表示取消／回调失败
//data: obj 可以是任意需要传递的对象
Routerfit.setResult(Routerfit.RESULT_OK, obj)
```

这句话你自己感觉写的习惯了,其实你破坏了一个正常界面应该用的 Activity.setResult(Activity.RESULT_OK,bundle);
其实这里你应该推荐作者在 `Fragment` 或者 `Activity` 预埋一个 `Fragment` 去跳转,然后就能接管 `onActivityResult` 了,这点才是大杀器好不好.当然了预埋 `Fragment`  的 `Context`  不能是 `Application`.但是换句话说用了 `Application` 的也不会去拿返回的数据,原生方法也是不支持的
而且这种方式不需要你在目标界面做任何的修改,同时更支持第三方和系统的界面.
还有就是可以传递任何对象这点也是不推荐的,我个人的建议是不推荐传递超出系统支持以外的对象,尽量的贴近系统.另外你提的有两点我今后的更新中也会考虑的,谢谢

**Comment by guozhiqiang123** [comment]
1.ARetrofit目前是支持标准的Uri跳转的；
2.关于跳转的时候携带参数的那个问题，我们在实际项目中的做法是在base模块中维护一张路由接口表，因为ARetrofit和Retrofit的用法基本一致，所以参数的构造基本在这张表中一目了然，在协同开发的时候，只有最后串联业务的时候才会调用同事写的路由方法，这也就意味着这个时候会先Git同步一次代码，所以不会存在同一activity注册了两个路由方法。因为我们的规范是路由方法名都是“skip+完整Activity名”，所以保证了这个路由接口表中所有跳转都是唯一的。
3.关于参数选填的问题，我们的解决方案是要么填默认值，要么在路由接口表中补充一个重载方法。因为只是补充了一个抽象方法，所以代码不会太多，而且会配合注释，所以也比较容易理解（因为在调用的使用发现自动补全有多个同名方法的时候，肯定会进去看注释，但是对于只有一个的，则直接调用，使用速度上快很多，这个我在把CC替换成ARetrofit的时候深有体会，一个中等大小的项目，我只用了一天半就把里面CC全替换干净了）
4.因为CC是面向协议的，ARetrofit算是面向接口的吧，所以CC路径还有action等字符串都是随意取名的，不规范也不会报错，虽然这么做自由程度很高，但是对于一个多人开发的团队来说，每个人的开发方式和习惯都不一样，如果公司再没有开发规范的文档，整个项目就乱七八糟，加上开发人员的流动，会导致项目越来越难以维护，效率也极低。所以有时候框架太自由也不是好事（解释为什么业务不可能永远是最开始那个开发者一直维护）。
5.关于调试，单模块调试还是很有必要的，一个项目可能拆分成二三十个业务模块，有时候整体运行都要很长时间。所以单独调试也会极大的提高效率。CC打包出现问题我一次都没有遇到过，有可能他们的使用姿势不正确。因为CC 2.x中即使没有依赖到科工程，也不会报错，如果粗心，就可能漏了这个模块
6.ARetrofit中setResult这个问题，的确这里有点让人难以理解，如果协同开发，会让同事在startActivity我写的业务的时候有些困惑，但还没有到不可维护的地步，因为startForResult的情况本来就很少 （相对越整个项目），跨模块的startForResult(调同事写的业务)情况就更少了，所以还没有到不可维护的地步，因为调同事写的业务的时候肯定会先捋清楚同事写的这一块的业务
7.另外使用简洁真的很有必要，因为不是所有刚入职的同事之前就已经使用过这款库，所以越简单的使用和配置，越是让人容易快速融入项目。毕竟我们开源的没法和大厂或者是官方的比，别人的用法再复杂，咱们都得学，惹不起！惹不起！
8.现在我们项目中，即使是在同一模块中也尽量采用路由进行跳转，而不用原生的，因为你不知道哪天业务和代码重构，这一块的代码就可能摞到另外一个模块中去了，所以简单实用就是王道！
9.谢谢采纳我的部分意见！！！

**Comment by xiaojinzi123** [comment]
> 1.ARetrofit目前是支持标准的Uri跳转的；
> 2.关于跳转的时候携带参数的那个问题，我们在实际项目中的做法是在base模块中维护一张路由接口表，因为ARetrofit和Retrofit的用法基本一致，所以参数的构造基本在这张表中一目了然，在协同开发的时候，只有最后串联业务的时候才会调用同事写的路由方法，这也就意味着这个时候会先Git同步一次代码，所以不会存在同一activity注册了两个路由方法。因为我们的规范是路由方法名都是“skip+完整Activity名”，所以保证了这个路由接口表中所有跳转都是唯一的。
> 3.关于参数选填的问题，我们的解决方案是要么填默认值，要么在路由接口表中补充一个重载方法。因为只是补充了一个抽象方法，所以代码不会太多，而且会配合注释，所以也比较容易理解（因为在调用的使用发现自动补全有多个同名方法的时候，肯定会进去看注释，但是对于只有一个的，则直接调用，使用速度上快很多，这个我在把CC替换成ARetrofit的时候深有体会，一个中等大小的项目，我只用了一天半就把里面CC全替换干净了）
> 4.因为CC是面向协议的，ARetrofit算是面向接口的吧，所以CC路径还有action等字符串都是随意取名的，不规范也不会报错，虽然这么做自由程度很高，但是对于一个多人开发的团队来说，每个人的开发方式和习惯都不一样，如果公司再没有开发规范的文档，整个项目就乱七八糟，加上开发人员的流动，会导致项目越来越难以维护，效率也极低。所以有时候框架太自由也不是好事（解释为什么业务不可能永远是最开始那个开发者一直维护）。
> 5.关于调试，单模块调试还是很有必要的，一个项目可能拆分成二三十个业务模块，有时候整体运行都要很长时间。所以单独调试也会极大的提高效率。CC打包出现问题我一次都没有遇到过，有可能他们的使用姿势不正确。因为CC 2.x中即使没有依赖到科工程，也不会报错，如果粗心，就可能漏了这个模块
> 6.ARetrofit中setResult这个问题，的确这里有点让人难以理解，如果协同开发，会让同事在startActivity我写的业务的时候有些困惑，但还没有到不可维护的地步，因为startForResult的情况本来就很少 （相对越整个项目），跨模块的startForResult(调同事写的业务)情况就更少了，所以还没有到不可维护的地步，因为调同事写的业务的时候肯定会先捋清楚同事写的这一块的业务
> 7.另外使用简洁真的很有必要，因为不是所有刚入职的同事之前就已经使用过这款库，所以越简单的使用和配置，越是让人容易快速融入项目。毕竟我们开源的没法和大厂或者是官方的比，别人的用法再复杂，咱们都得学，惹不起！惹不起！
> 8.现在我们项目中，即使是在同一模块中也尽量采用路由进行跳转，而不用原生的，因为你不知道哪天业务和代码重构，这一块的代码就可能摞到另外一个模块中去了，所以简单实用就是王道！
> 9.谢谢采纳我的部分意见！！！

目前 [Component](https://github.com/xiaojinzi123/Component) 也支持接口的编写了.这个好的方面我已经吸收了,至于单独运行,其实和组件化方案无关,可以选择 CC 的单独运行的方案.
其他方面 aretrofit 和本项目比有下面分方面欠考虑：

1.  路由代码的可执行线程(我的是任务线程调用都可以)
2. 跳转拿 ActivityResult 的方式更好,支持系统和第三方
3. 目标界面的 Intent 可以自定义
4. 路由关联的 Activity 或者 Fragment 销毁了,路由会自动取消
5. bug几乎没有,公司用了快一年了
6. Idea 插件的配套
7. 路由的调用结果,我的是统一都是 callback 方式返回,并且回调中你能拿到最原始的 RouterRequest,可能有时候需要用
8. 拦截器方面设计的更好,页面拦截器这个简直不要太好用
9. 路由的返回值,我的永远就一个 `NavigationDisposable`,可用于手动取消本次路由
10. 支持 `androidx` 和 'Rxjava',依赖 xxx-rx 版本就完美支持了 rxjava,版本号后面 + androidx 就支持了 `androidx`
11. rx版本中并且帮助您忽略了内置的异常,让您使用的时候可以不关心错误的回调, RxJava 默认不处理错误会奔溃!

以上的好处还请你熟悉,除了刚刚最近吸收的面相接口的方式,其他方面你可以比较下.还是有很多方面的好处的.

**Comment by guozhiqiang123** [comment]
我也一直在跟楼主这个项目，给楼主积极更新的精神点赞！！！

**Comment by guozhiqiang123** [comment]
感觉你这个库，完全有能力替代ARouter,但是还需要继续推广，继续优化性能。性能方面我还没有具体测试过，有点妄言。祝成功！！！

**Comment by xiaojinzi123** [comment]
谢谢,你们的建议是我维护和前进的动力,谢谢
