### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by Bacchuc** [xiaojinzi123/RouterGoPlugin#2]
希望可以修复一下正向跳转不显示了的问题，谢谢！

**Comment by xiaojinzi123** [comment]
新版本已经修复,过两天在 `Idea Plugin` 仓库中搜索 `RouterGo` 就行啦<br/>
或者你可以点击下载最新版 
[RouterGoPlugin-1.1.jar](https://github.com/xiaojinzi123/RouterGoPlugin/releases/download/v1.1/RouterGoPlugin-1.1.jar)

**Comment by Bacchuc** [comment]
嘿嘿嘿，么么哒
