### ISSUE TITLE
在Android Studio中无法下载插件

### ISSUE THREAD

**Issue by zhoujia456888** [xiaojinzi123/RouterGoPlugin#3]
我在Android Studio中搜索RouterGo。界面上没有显示插件下载。然后我尝试下载RouterGoPlugin-1.2.1文件进行本地安装，结果提示我不兼容？，我上 [IDEA插件仓库](https://plugins.jetbrains.com/plugin/12519-routergo/versions)下载ZIP，本地安装也提示不兼容。
第一张图是直接搜索，第二张图是本地安装jar，第三张是我的AS版本信息
![TIM截图20190705103333](https://user-images.githubusercontent.com/7905253/60694607-355c1b80-9f11-11e9-9876-c3137b4e9d3f.png)

![TIM截图20190705103933](https://user-images.githubusercontent.com/7905253/60694619-3ee58380-9f11-11e9-9422-2fce0a64dcac.png)

![TIM截图20190705104035](https://user-images.githubusercontent.com/7905253/60694643-59b7f800-9f11-11e9-926d-0b4c145dff15.png)

**Comment by zhoujia456888** [comment]
你们是用的新的测试版本的Android Studio打包的jar吗。我看ideac仓库里面aroutergo的版本是build 191.5109 — 191.*这个版本是不是AndroidStudio3.5？
![image](https://user-images.githubusercontent.com/7905253/60694982-a5b76c80-9f12-11e9-8b59-7b4b5cb0a4c3.png)

**Comment by xiaojinzi123** [comment]
我这周发布一个支持比较低版本的插件, 或者你升级一下 idea 到 3.5
