### ISSUE TITLE
关于封装跳转方法的问题

### ISSUE THREAD

**Issue by Android-wangmeng** [xiaojinzi123/RouterGoPlugin#5]
我把跳转的代码自己封装了一下，这样的话，调用该方法并传入path，就不会出现跳转图标了。
请问有没解决办法？

**Comment by xiaojinzi123** [comment]
这个就没办法喽, 大哥, 因为 idea 插件获取不到值了. 不是常量的值就没法获取到. 这个无解, 大哥. 非常抱歉解决不了你的问题...
