### ISSUE TITLE
AndroidStudio4.1.2 插件不兼容

### ISSUE THREAD

**Issue by tangjiaqq** [xiaojinzi123/RouterGoPlugin#7]
AndroidStudio4.1.2 插件不兼容

**Comment by xiaojinzi123** [comment]
不好意思, 这个插件的更新很耗费时间和精力. 这边也是空闲时间维护的. 给您带来的不便还请谅解. 
因为 AS 基本每次的更新可能我都得维护. 也不知道那些写了好几年还能用的那些插件是怎么写的...

**Comment by tangjiaqq** [comment]
我抽空去研究一下

**Comment by xiaojinzi123** [comment]
可以在我代码基础上研究. 还有就是官方的 Android 插件也是很好的一个研究对象. 里面对应的功能你通过搜搜字符串可以找到

**Comment by xiaojinzi123** [comment]
这个插件我有空会更新到 4.1.2 的

**Comment by tangjiaqq** [comment]
好的
