### ISSUE TITLE
Android studio4.2.1插件不兼容

### ISSUE THREAD

**Issue by Lianruoxia** [xiaojinzi123/RouterGoPlugin#8]
刚准备将项目转入Component，结果下载插件无法安装，还有通过studio搜索不到该插件，在https://plugins.jetbrains.com/androidstudio搜索能够找到，但是比GitHub上版本高，而且同样不兼容
![image](https://user-images.githubusercontent.com/12423171/118779117-52a7f200-b8bd-11eb-8bd6-31beeb0dcbc4.png)

**Comment by xiaojinzi123** [comment]
插件的维护比较耗费精力. 要支持 kotlin 和 java. 
因为这个插件一直都是业余时间维护的, 所以不能一直更新到最新的版本. 
我也很奇怪, 为什么 Idea 的各个版本之间的兼容性会这么差....

但是说白了这个是一个辅助工具, 没有这个不影响 Component 的使用. 只不过提供了一点点的方便而已.

**Comment by xiaojinzi123** [comment]
支持 Android Studio 4.2.1 的已经发布. 可能要过几天才能下载. AS 中搜索 RouterGo 就可以. 已经提交审核

**Comment by Lianruoxia** [comment]
多谢

**Comment by xiaojinzi123** [comment]
我看已经审核过了, 可以下载了
